### ISSUE TITLE
Some Users Cannot Enable Gravatars

### ISSUE THREAD

**Issue by scottalanmiller** [julianlam/nodebb-plugin-gravatar#1]
For most users, Gravatars just worked after the move to 1.0.3 (under.0.9.0.)  But some users have found that they are now unable to get Gravatars to work.  We are compiling a list of uses who are attempting to get them working without success:

http://mangolassi.it/topic/6752/who-has-gravatar-issues

**Comment by barisusakli** [comment]
I think using https://github.com/emerleite/node-gravatar would solve some of those issues, probably related to url generation and the rating system etc.

**Comment by julianlam** [comment]
Seems like issue was the email not hashed properly, and a reset of the email caused gravatars to function properly again.

**Comment by julianlam** [comment]
Possibly different encoding on migration? Who knows.
